services:
  mongodb:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_URL: mongodb://mongodb:27017
      DB_NAME: pdf_extractext
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
